require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QualificationsController do

  # This should return the minimal set of attributes required to create a valid
  # Qualification. As you add validations to Qualification, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all qualifications as @qualifications" do
      qualification = Qualification.create! valid_attributes
      get :index
      assigns(:qualifications).should eq([qualification])
    end
  end

  describe "GET show" do
    it "assigns the requested qualification as @qualification" do
      qualification = Qualification.create! valid_attributes
      get :show, :id => qualification.id.to_s
      assigns(:qualification).should eq(qualification)
    end
  end

  describe "GET new" do
    it "assigns a new qualification as @qualification" do
      get :new
      assigns(:qualification).should be_a_new(Qualification)
    end
  end

  describe "GET edit" do
    it "assigns the requested qualification as @qualification" do
      qualification = Qualification.create! valid_attributes
      get :edit, :id => qualification.id.to_s
      assigns(:qualification).should eq(qualification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Qualification" do
        expect {
          post :create, :qualification => valid_attributes
        }.to change(Qualification, :count).by(1)
      end

      it "assigns a newly created qualification as @qualification" do
        post :create, :qualification => valid_attributes
        assigns(:qualification).should be_a(Qualification)
        assigns(:qualification).should be_persisted
      end

      it "redirects to the created qualification" do
        post :create, :qualification => valid_attributes
        response.should redirect_to(Qualification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved qualification as @qualification" do
        # Trigger the behavior that occurs when invalid params are submitted
        Qualification.any_instance.stub(:save).and_return(false)
        post :create, :qualification => {}
        assigns(:qualification).should be_a_new(Qualification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Qualification.any_instance.stub(:save).and_return(false)
        post :create, :qualification => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested qualification" do
        qualification = Qualification.create! valid_attributes
        # Assuming there are no other qualifications in the database, this
        # specifies that the Qualification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Qualification.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => qualification.id, :qualification => {'these' => 'params'}
      end

      it "assigns the requested qualification as @qualification" do
        qualification = Qualification.create! valid_attributes
        put :update, :id => qualification.id, :qualification => valid_attributes
        assigns(:qualification).should eq(qualification)
      end

      it "redirects to the qualification" do
        qualification = Qualification.create! valid_attributes
        put :update, :id => qualification.id, :qualification => valid_attributes
        response.should redirect_to(qualification)
      end
    end

    describe "with invalid params" do
      it "assigns the qualification as @qualification" do
        qualification = Qualification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Qualification.any_instance.stub(:save).and_return(false)
        put :update, :id => qualification.id.to_s, :qualification => {}
        assigns(:qualification).should eq(qualification)
      end

      it "re-renders the 'edit' template" do
        qualification = Qualification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Qualification.any_instance.stub(:save).and_return(false)
        put :update, :id => qualification.id.to_s, :qualification => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested qualification" do
      qualification = Qualification.create! valid_attributes
      expect {
        delete :destroy, :id => qualification.id.to_s
      }.to change(Qualification, :count).by(-1)
    end

    it "redirects to the qualifications list" do
      qualification = Qualification.create! valid_attributes
      delete :destroy, :id => qualification.id.to_s
      response.should redirect_to(qualifications_url)
    end
  end

end
